services:
  - type: web
    name: treasure-workbench-watermark
    env: python
    region: singapore
    buildCommand: pip install -r watermark-server/requirements.txt
    startCommand: cd watermark-server && python main.py
    envVars:
      - key: PORT
        value: 5002
      - key: PYTHON_VERSION
        value: 3.11.0
